# Generated by Django 3.2.19 on 2023-06-06 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post_usercomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='usercomments',
        ),
        migrations.AddField(
            model_name='post',
            name='user_comments',
            field=models.ManyToManyField(blank=True, related_name='blog_user_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
