# Generated by Django 3.2.19 on 2023-06-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230606_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_comments',
        ),
    ]
