# Generated by Django 3.2.19 on 2023-06-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230614_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='undefined', max_length=200),
        ),
    ]
