# Generated by Django 3.2.19 on 2023-06-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_contact_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
