# Generated by Django 3.2.19 on 2023-06-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20230620_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='armor',
        ),
    ]
